config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about'

  get 'pages/contact'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios
  get 'angular-item', to: 'portfolios#angular'
  get 'ruby-on-rails', to: 'portfolios#rubyonrails'
  root to: 'portfolios#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    guest = Guest.new
    guest.name = "Guest"
    guest.email = "guest@guest.net"
    guest
  end

end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :email
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  validates_presence_of :title, :subtitle, :body, :main_image, :thumb_image

  after_initialize :set_default

  def set_default
    self.main_image ||= "http://via.placeholder.com/350x150"
    self.thumb_image ||= "http://via.placeholder.com/350x100"
  end

  def self.angular
    where(subtitle: 'angular')
  end

  scope :ruby_on_rails, -> {where(subtitle: 'ruby_on_rails')}
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  def firstname
    self.name.split.first
  end

  def lastname
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include PageContent
  include CurrentUserConcern
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    guest = GuestUser.new
    guest.name = "Guest"
    guest.email = "guest@guest.net"
    guest
  end

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

    included do
        before_action :configure_permitted_parameter, if: :devise_controller?
    end


  def configure_permitted_parameter
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end


end

app/controllers/concerns/page_content.rb
module PageContent
  extend ActiveSupport::Concern

  included do
    before_action :set_default_title
    # '@page_title' in "application.html.erb"
    def set_default_title
      @page_title = "Welcome to My Page"
    end
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @portfolio = Portfolio.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolios'
  access all: [:show, :index, :rubyonrails, :angular],
         user: {except: [:destroy, :new, :create, :edit, :update]},
         site_admin: :all

  def index
    @portfolios = Portfolio.all
    @page_title = "Jbaik's Portfolio"
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html {redirect_to portfolio_path(@portfolio), notice: "Your portfolio item is now live."}
      else
        format.html {render :new}
      end
    end
  end

  def show
    @portfolio = Portfolio.find(params[:id])
    @page_title = Portfolio.find(params[:id]).title
  end

  def edit
    @portfolio = Portfolio.find(params[:id])
  end

  def update
    @portfolio = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html {redirect_to portfolio_path(@portfolio), notice: "Your portfolio item is now updated."}
      else
        format.html {render :edit}
      end
    end
  end

  def angular
    @portfolio_angular = Portfolio.angular
  end

  def rubyonrails
    @portfolio_ruby_on_rails = Portfolio.ruby_on_rails
  end

  def destroy
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title, :subtitle, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # if there is a problem showing only log in button use () +
  def user_authenticate_button
    if current_user.is_a?(GuestUser)
      (link_to 'Register', new_user_registration_path) +
      ('<br>'.html_safe) +
      (link_to 'Log In', new_user_session_path)

    else
      link_to 'Log out', destroy_user_session_path, method: :delete

    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= user_authenticate_button %>
    <%= render "/shared/nav_button" %>
    <%= yield %>

    <p>
        <% if session[:source]  %>
          <%= "Thank you for visiting me from #{session[:source]} " %>
        <% end %>
        </p>
  </body>
</html>

app/views/layouts/portfolios.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= user_authenticate_button %>
    <%= render "shared/nav_button" %>
    <%= yield %>

    <p>
        <% if session[:source]  %>
          <%= "Thank you for visiting me from #{session[:source]} " %>
        <% end %>
        </p>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
  <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
    <header class="masthead mb-auto">
      <div class="inner">
        <h3 class="masthead-brand">Cover</h3>
        <nav class="nav nav-masthead justify-content-center">
          <a class="nav-link active" href="#">Home</a>
          <a class="nav-link" href="#">Features</a>
          <a class="nav-link" href="#">Contact</a>
        </nav>
      </div>
    </header>

    <main role="main" class="inner cover">
      <h1 class="cover-heading">Cover your page.</h1>
      <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
      <p class="lead">
        <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
      </p>
    </main>

    <footer class="mastfoot mt-auto">
      <div class="inner">
        <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      </div>
    </footer>
  </div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio List</h1>
<%= link_to 'Add New', new_portfolio_path if logged_in?(:admin, :customer, :etc)  %>


<p><% @portfolio_angular.each do |port| %></p>
        <h2><%=port.title  %></h2>
        <hr>
            <%=port.subtitle  %><br>
            <%=port.body  %><br>
            <%=image_tag port.main_image  %><br>
            <%=image_tag port.thumb_image  %><br>
          <%= link_to 'EDIT', edit_portfolio_path(port) if logged_in?(:admin, :customer, :etc)  %><br>
          <%= link_to 'SHOW', portfolio_path(port) %>
          <hr>
      <% end %>

app/views/portfolios/destroy.html.erb
<h1>Portfolios#destroy</h1>
<p>Find me in app/views/portfolios/destroy.html.erb</p>

app/views/portfolios/edit.html.erb
<h1>Edit your portfolio?</h1>

<%= form_for @portfolio do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :subtitle %>
  <%= f.text_field :subtitle %><br>

  <%= f.label :body %>
  <%= f.text_area :body %><br>

  <%= f.submit %>
<% end %>

app/views/portfolios/index.html.erb
<h4>Hi! <%= current_user.name %></h4>
<h1>Portfolio List</h1>
<%= link_to 'Add New', new_portfolio_path if logged_in?(:admin, :customer, :etc)  %>


<p><% @portfolios.each do |port| %></p>
        <h2><%=port.title  %></h2>
        <hr>
            <%=port.subtitle  %><br>
            <%=port.body  %><br>
            <%=image_tag port.main_image  %><br>
            <%=image_tag port.thumb_image  %><br>
          <%= link_to 'EDIT', edit_portfolio_path(port) if logged_in?(:admin, :customer, :etc)  %><br>
          <%= link_to 'SHOW', portfolio_path(port) %>
          <hr>
      <% end %>

app/views/portfolios/new.html.erb
<h1>Portfolios#new</h1>
<%= form_for @portfolio do |f| %>
<div class="">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class="">
  <%= f.label :subtitle %>
  <%= f.text_field :subtitle %>
</div>

<div class="">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>

<div class="">
  <%= f.submit %>
</div>
<% end %>

app/views/portfolios/rubyonrails.html.erb
<h1>Rails Portfolio</h1>
<%= link_to 'Add New', new_portfolio_path if logged_in?(:admin, :customer, :etc)  %>


<p><% @portfolio_ruby_on_rails.each do |port| %></p>
        <h2><%=port.title  %></h2>
        <hr>
            <%=port.subtitle  %><br>
            <%=port.body  %><br>
            <%=image_tag port.main_image  %><br>
            <%=image_tag port.thumb_image  %><br>
          <%= link_to 'EDIT', edit_portfolio_path(port) if logged_in?(:admin, :customer, :etc)  %><br>
          <%= link_to 'SHOW', portfolio_path(port) %>
          <hr>
      <% end %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio.title %> </h1>
<hr>
<h3><%= @portfolio.subtitle %></h3>
<br>
<h4><%= @portfolio.body %></h4>

<%= image_tag @portfolio.main_image %><br>
<%= image_tag @portfolio.thumb_image %>
<br>
<%= link_to 'List', portfolios_path %>
<%= link_to 'Edit', edit_portfolio_path(@portfolio) if logged_in?(:admin, :customer, :etc)  %>

app/views/shared/_nav_button.html.erb
<div>
  <div><%= link_to 'HOME', root_path %>
  <div><%= link_to 'ABOUT', pages_about_url %>
  <div><%= link_to 'CONTACT', pages_contact_url %><
</div>